### ISSUE TITLE
Feature Request:  Ability for pysigsci to clear all flagged ips for a site or sites

### ISSUE THREAD

**Issue by jdempsey77** [foospidy/pysigsci#12]
Ability for pysigsci to clear all flagged ips for a site or sites.  If a rule or rules go haywire be good to clear out all of the flagged ip addresses via pysigsci

**Comment by foospidy** [comment]
I agree this will be a nice feature. Looking into it.

In the meantime, I do have a script solution for this posted here:

https://gist.github.com/foospidy/576dd824cb2f1026b9515a0969b11d6f

**Comment by foospidy** [comment]
This has been added. Download the latest, `pip install --upgrade pysigsci`

Command to use is `pysigsci --expire-all-site-events --site <site>`
