### ISSUE TITLE
delete_corp_user() doesn't delete users

### ISSUE THREAD

**Issue by ring-nsoracco** [foospidy/pysigsci#18]
howdy.  When using what I presume is the latest module here from pypi, when I call `delete_corp_user()`, the user doesn't actually delete.  I have to manually delete the user from the console.  Not sure what kind of debugging you need, but this doesn't appear to do what it says on the tin.

**Comment by ring-nsoracco** [comment]
Can't reproduce, closing.  Might have been result of either:
* a string conversion bug that made two sets look identical at the time of comparison but *weren't* actually identical
* an issue with when the user was created (back in 2018) and having never accepted their invite.

Also, you don't need a site assigned to the instantiated API call, as I thought I did.

**Comment by foospidy** [comment]
Hey @ring-nsoracco, apologies for just now looking at this. I'm glad it is working for you now. Let me know if you run into any other issues. Thanks!
