### ISSUE TITLE
Support for the replace_list_by_id?

### ISSUE THREAD

**Issue by ring-nsoracco** [foospidy/pysigsci#19]
It doesn't appear that the [replace_list_by_id](https://docs.signalsciences.net/api/#_corps__corpName__lists__id__put) API call is supported by this code. working on a PR.

**Comment by ring-nsoracco** [comment]
So I spent a couple hours on this, and can't quite figure out where I'm going wrong. I looked at the [api docs](https://docs.signalsciences.net/api/#_corps__corpName__lists__id__put), and the method I wrote is as follows:
```
    def replace_corp_rule_lists(self, identifier, data):
        """
        Replace a corp list wholesale by ID
        https://docs.signalsciences.net/api/#_corps__corpName__lists__id__put
        PUT /corps/{corpName}/lists/{id}
        """
        return self._make_request(
            endpoint="{}/{}/lists/{}".format(self.ep_corps,
                                             self.corp,
                                             identifier),
            json=data,
            method="PUT")
```

Which looks right, based on other methods that translate to PUT calls. 

Yet I receive a 400 response with an error message of: '{"message":"Problems parsing JSON"}\n'

The blob I'm trying to PUT:
```
json.dumps({'entries':['4.5.6.0/24']}
```

Here's some test-driver code so I have something to breakpoint, with the pii bits removed:
```
import os
import sys
import json
import sigsciapi

(email, token) = ('myusername','my-token')
corp = 'mycorp'
ssa = sigsciapi.SigSciApi(email=email,api_token=token)
ssa.corp = corp
the_data = json.dumps({'entries':['4.5.6.0/24']})
the_list = ssa.get_corp_rule_list(identifier='corp.my-test')
print(the_list)
# fails with 400 response.
ssa.replace_corp_rule_lists(identifier='corp.my-test',data=the_data)
```

Any idea where I messed up?

**Comment by foospidy** [comment]
Sorry for a delayed response! 

I just used your code example to test with. I think your  json data is not complete. I used the example json payload from the docs and it worked.

```
new_list = {
        "description": "Some IPs we're still putting in a list",
        "entries": [
            "4.5.6.7",
            "1.2.3.4",
            "9.8.7.6"
        ]}
```

Go a head and submit a pull request. Or if you like, I can add the methods for corp and site.

* Description field is likely required.

**Comment by ring-nsoracco** [comment]
tried adding a description. 
`the_data = json.dumps({'entries':['2.2.2.0/24'], 'description':'this is required'})`

Same error 400, error parsing JSON.

Also, just in case it had an edge case around a list of one, I tried with a second address in the list, same problem.

This code works but is super hacky and thoroughly far from ideal:
```
temp_file = '/tmp/the-list'
tmp_fh = open(temp_file,'w+')
tmp_fh.write(the_data)
tmp_fh.close()
command = 'curl -H "x-api-user:{}" -H "x-api-token:{}" -H "Content-Type: application/json" -T "{}" "https://dashboard.signalsciences.net/api/v0/corps/ring/lists/{}"'.format(email, token, temp_file, list_id)
command = shlex.split(command)
process_info = subprocess.run(command, shell=False, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
```

I feel like this is a problem with my specific account, or maybe a bug in python urllib3, since this is running in Ubuntu 18.04 which as a fairly crusty python 3.6 installation instead of 3.7 or 3.8.  Requests is probably being dumb.  I will try in a newer python version.

PR submitted #20

**Comment by ring-nsoracco** [comment]
Tried this in python3.8, requests 2.22, still fails with error 400.  Only thing I can think of, if it works for you, and not for me, that my account has something weird going on.

In my normal environment, python 3.6 and requests 2.18.4, the problem still exists.

**Comment by foospidy** [comment]
Ok, I think I understand why. I missed this before because it's subtle. You don't need to call json.dumps(), the json object is handled in self._make_request() when the call to requests() is made. Example: https://github.com/foospidy/pysigsci/blob/master/pysigsci/sigsciapi/sigsciapi.py#L69

I've been tangled in this sort of thing many times before, sorry I didn't catch it sooner :-(. Let me know if this resolves it for you.

**Comment by ring-nsoracco** [comment]
Hah, yep, that was it.  :)  Thanks!  My test works perfectly now.  Not sure why I felt the need to encode it first either..  eta: #20 is definitely safe to merge now.

**Comment by ring-nsoracco** [comment]
*n.b.:* added a site version too.

**Comment by ring-nsoracco** [comment]
lastly, I think I figured out why I pre-encoded it.  the parameter name for the `_make_request()` method is called `json` so I think I just presumed that's what data it expected.
