### ISSUE TITLE
key['data'] not found when comparing configs 

### ISSUE THREAD

**Issue by marquosz** [foospidy/pysigsci#26]
Following the Audit procedure, mentioned [here](https://www.signalsciences.com/blog/auditing-signal-sciences-configuration/), we face this error when we tried running 
`pysigscia --compare site1 > report.txt`

Our environment, doesn't have `advanced_rules` enabled

```
Traceback (most recent call last):
  File "/usr/local/bin/pysigscia", line 263, in <module>
    main()
  File "/usr/local/bin/pysigscia", line 234, in main
    diff_config(
  File "/usr/local/bin/pysigscia", line 67, in diff_config
    config1 = json.load(infile)['data']
KeyError: 'data'
```

**Comment by foospidy** [comment]
patch https://github.com/foospidy/pysigsci/commit/60e0a6ea13b39b84aee01245ef40378114d7754f

**Comment by foospidy** [comment]
published https://pypi.org/project/pysigsci/3.18.1/
